gen-service-protos:
	protoc --go_out=. \
  		--go-grpc_out=. \
  		--proto_path=yandex_protos \
  		yandex.proto

gen-create-protos:
	protoc --go_out=. \
  		--go-grpc_out=. \
  		--proto_path=protos \
  		creations.proto
